version: '3.3'
services:
  db:
    image: mysql:5.5.62
    restart: always
    environment:
      MYSQL_DATABASE: 'sunnydb01'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'sxw'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Hit.5674754'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Hit.5674754'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    container_name: adm1
    ports:
      - 8098:8080
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

# Names our volume
volumes:
  mysql-db: 
    driver: local # a volume will be created automatically
